{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-stack.fullname" . }}-mcp-server-service
  labels:
    {{- include "todo-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "todo-stack.selectorLabels" . | nindent 4 }}
    app: todo-mcp-server
{{- end }}