{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-stack.fullname" . }}-backend-service
  labels:
    {{- include "todo-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "todo-stack.selectorLabels" . | nindent 4 }}
    app: todo-backend
{{- end }}